### ISSUE TITLE
PyTorch ResNet-50 with Imagenet100

### ISSUE THREAD

**Issue by parthjdoshi** [KaidiXu/auto_LiRPA#16] opened 2021-11-29 00:20 UTC
Hello,

Thank you for the great implementations.
I am trying to train a ResNet-50 model, as defined in PyTorch, with 100 classes from the entire ImageNet dataset, at the original resolution of 224x224, under the Crown-IBP bounds.

The changes that we made to the imagenet training example from the repo are as follows:
```
    model_ori = torch_models.resnet50(pretrained=False)
    in_features = model_ori.fc.in_features
    model_ori.fc = nn.Linear(in_features=in_features, out_features=100)

    r = [[label] for label in range(0, 1000, 10)]
    custom_dataset = CustomImageNet('/home/pdoshi/imagenet100', custom_grouping=r)
    
    train_data, test_data = custom_dataset.make_loaders(workers = 4, batch_size = 16)
```
The CustomImageNet class is from the robustness package and gives us the data loaders.

The code runs properly when we are not using the bound loss function during the initial iterations, but once the epochs enter the phase of robust training with the bounds, we get the following error.

The error that we are facing is
```
Traceback (most recent call last):
  File "/home/pdoshi/imagenet_training_crown_ibp.py", line 335, in <module>
    main(args)
  File "/home/pdoshi/imagenet_training_crown_ibp.py", line 293, in main
    Train(model_loss, t, train_data, eps_scheduler, norm, True, opt, args.bound_type, loss_fusion=True)
  File "/home/pdoshi/imagenet_training_crown_ibp.py", line 164, in Train
    lb, robust_ce = get_bound_loss(x=x, c=c)
  File "/home/pdoshi/imagenet_training_crown_ibp.py", line 98, in get_bound_loss
    clb, cub = model(method_opt="compute_bounds", IBP=False, C=c, method='backward',
  File "/home/pdoshi/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pdoshi/venv/lib/python3.9/site-packages/auto_LiRPA-0.2-py3.9.egg/auto_LiRPA/bound_general.py", line 2004, in forward
  File "/home/pdoshi/venv/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/pdoshi/venv/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/pdoshi/venv/lib/python3.9/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/pdoshi/venv/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/pdoshi/venv/lib/python3.9/site-packages/auto_LiRPA-0.2-py3.9.egg/auto_LiRPA/bound_general.py", line 147, in __call__
    return self.compute_bounds(**kwargs)
  File "/home/pdoshi/venv/lib/python3.9/site-packages/auto_LiRPA-0.2-py3.9.egg/auto_LiRPA/bound_general.py", line 1413, in compute_bounds
    return self._backward_general(C=C, node=final, root=root, bound_lower=bound_lower, bound_upper=bound_upper,
  File "/home/pdoshi/venv/lib/python3.9/site-packages/auto_LiRPA-0.2-py3.9.egg/auto_LiRPA/bound_general.py", line 1661, in _backward_general
    A, lower_b, upper_b = l.bound_backward(l.lA, l.uA, *l.inputs)
  File "/home/pdoshi/venv/lib/python3.9/site-packages/auto_LiRPA-0.2-py3.9.egg/auto_LiRPA/operators/convolution.py", line 493, in bound_backward
    lA = last_lA.expand(list(last_lA.shape[:-2]) + [H, W]) / (H * W)
AttributeError: 'NoneType' object has no attribute 'expand'

```

**Comment by shizhouxing** [comment] 2021-11-29 02:11
Hi @parthjdoshi , thanks for raising this issue with detailed information! It looks like the issue is due to that we missed a check for unused bounds in the pooling operation (Lower bound is not used in your call, so `last_lA` here is `None`, and we need to check it to skip computing `lA`).

We'll try to push a quick fix. @YihanWang617

**Comment by shizhouxing** [comment] 2021-12-01 05:54
Hi @parthjdoshi , we have pushed the fix to the `develop` branch. Could you please switch to the `develop` branch, pull the latest code, and reinstall `auto_LiRPA`? You may also re-clone and reinstall the library via:

```bash
git clone -b develop git@github.com:KaidiXu/auto_LiRPA.git
cd auto_LiRPA
python setup.py install
```

Please feel free to let us know in case that you still meet any issue. Thanks!

**Comment by parthjdoshi** [comment] 2021-12-01 18:34
Hey @shizhouxing 

Thank you for the quick fix. I'll try it out today and I'll close the issue if I don't face any more problems.

**Closed** 2021-12-07 16:24 UTC
